results_topic: "/dialogflow_client/results"
requests_topic: "/dialogflow_text"
text_topic: "/dialogflow_text"
project_id: "bear-in-mind-26c28"
play_audio: false
use_audio_server: false
server_name: "127.0.0.1"
port: 4444
debug: false
